### PR TITLE
Added exchange rate implementations for API v2

### PR DESCRIPTION
**Pull request by bmhenry**

### CODE REVIEW

**Comment by JuxhinDB** [comment]
Hey @bmhenry, thanks for the PR! Everything looks good so far, just some minor requests:

1. Do you mind removing the `pass` at the end of the [class](https://github.com/JuxhinDB/gw2-api-interface/pull/9/files#diff-3802b37e089e5c757fbea7ffc6923ddbR173). Same would apply for the other class. It's not needed there if there is a custom implementation. 

2. Would you be able to create some basic unit test, to give a better understanding as to what you are expecting from the API? Something similar to the unittests for [continents](https://github.com/JuxhinDB/gw2-api-interface/blob/master/test/test_continents.py). Doesn't have to be that verbose or complex, just enough to know what to expect from the API. If you need help ofcourse do let me know.

Thanks again!

**Comment by JuxhinDB** [comment]
@bmhenry This looks great. Unfortunately there seems to be some intermittent issue with some of the TravisCI jobs that I need to eventually take a closer look into. Is there anything else you would like to implement before I merge this PR in master?

**Comment by bmhenry** [comment]
@JuxhinDB Gotcha, I was wondering about that. Haven't used mock requests before; I just copied what was in the continents test. Nope, not for this. Will probably implement transactions next, but I'll put it in a separate PR.

**Comment by JuxhinDB** [comment]
@bmhenry Between us, nor have I ever mocked requests. I normally work with local APIs, so unittests tend to be actual calls to a local instance which we don't have the luxury of here. @shoeffner however was great enough to show us how to implement it. 

That said, this looks good and I thank you again for the PR. Merging.

**Pull request merged**
