### PR TITLE
Making the library pip-installable

### PR DESCRIPTION
**Pull request by shoeffner**
This pull request performs the following changes to make the package installable:
- Adding a setup.py.
- Adding a version number (0.5.0).
- Converting the README.md to a README.rst, adding some syntax highlighting and installation instructions.
- Renaming client -> gw2api.

Adding a setup.py file with a version number (I arbitrarily chose 0.5.0, but this can be changed) and requirements handling. This allows for e.g. `pip install -e https://github.com/JuxhinDB/gw2-api-interface#egg=gw2api`.

I renamed the client directory to `gw2api` as it seems slightly less generic. However, this breaks things, so if you don't want this to break, I can change it back. Also note that there is already a package gw2api on PyPI, so maybe gw2-api-interface might be the best choice?

In case you ever plan to upload it to PyPI, I also converted the README to an rst file (last time I checked, PyPI did not support markdown, but it's not impossible that the new version can do it). I also added some syntax highlighting and installation instructions as mentioned above.

Please let me know what you think of these changes.

### CODE REVIEW

**Comment by JuxhinDB** [comment]
Hi @shoeffner. First of all, many thanks for the PR! I did not expect much, if any traction on this project (was just a weekend side thing). 

Overall, I'm very much OK with the PR as it's mostly refactoring. Just a few things I'd like your opinion/clarification on:

1. The RST format looks good, just a few weirdly rendered bits and bobs such as:

    - Verify SSL? (The ? appears invalid)
    - Using Fiddler header seems to be incorrectly formatted? (Using `Fiddler<http://www.telerik.com/fiddler>`__:)
    - The UUID at the very bottom seems incorrectly formatted (0CB3B1A7-4C70-E611-80D3-E4115BE8BBE8)

2. We can do the refactoring from `client` to `gw2api` which I agree, given the specific client, makes sense to be more explicit. However if this breaks things, would you mind setting up a few test cases to keep it stable, then refactoring? 

Otherwise if this is too much work (and I understand), it's best we keep it as it is. I may decide in the future to add the test suite myself.

3. Since there is already a package named `gw2api` I would prefer naming it `gw2-api-client` as in my mind, it's more that, than an interface (though can be used as one). 

Thanks again, please let me know what you think.

**Comment by shoeffner** [comment]
1. The bits in the code sections (? and UUID) are because the code is not proper python (it uses `>>>` to denote the output). I will think about a solution to this. The fiddler header is broken, I will fix that.
2. Nothing testable inside the library breaks, since the import statement changes. The project itself stays stable. But whoever currently uses this library runs into trouble when trying to update the library. A possibility to avoid this, would be to allow both imports (`import client` and `import gw2api`) and e.g. output a deprecation warning when client is imported.
3. I will change the name to gw2-api-client. Should the import be `gw2api`, `gw2_api_client`, `gw2apiclient` or anything else?

**Comment by shoeffner** [comment]
1. The outputs are now non-highlighted code blocks. The fiddler link renders properly.
2. No action taken.
3. The name of the package is already "GuildWars2 API Client". I kept the import as `gw2api` for now and adjusted the remaining occurrences inside the README.

**Comment by JuxhinDB** [comment]
Hey @shoeffner - thanks again. This looks great. I agree with .1 and .3, regarding .2 ideally we would go down the `DeprecationWarning` route. However I feel that given the project, we can skip right ahead given that it's still very young and not yet "stable". 

So just confirm with me when you're happy with the module refactor, I'll take a look and if so merge. :-)

**Comment by shoeffner** [comment]
This sounds good, thank you!

**Comment by JuxhinDB** [comment]
Merged the PR. Thanks again!

**Comment by JuxhinDB** [comment]
@shoeffner -- Just letting you know that I uploaded it to PyPi - https://pypi.org/project/GuildWars2-API-Client/

**Comment by shoeffner** [comment]
Thanks a lot!

However, I do have a problem with the wheels, I guess.

When I try to run

```python
from gw2api import GuildWars2Client

api = GuildWars2Client()
print(api.build.get())
```

The installation via git `pipenv install git+https://github.com/JuxhinDB/gw2-api-interface.git#egg=GuildWars2-API-Client` works fine:

```
{'id': 89064}
```

But if I try using the PyPI version, that is `pipenv install GuildWars2-API-Client`, I can't run it properly:

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    api = GuildWars2Client()
  File "/Users/shoeffner/.local/share/virtualenvs/t-RT3T0cTf/lib/python3.6/site-packages/gw2api/__init__.py", line 39, in __init__
    self.__build_object_clients()
  File "/Users/shoeffner/.local/share/virtualenvs/t-RT3T0cTf/lib/python3.6/site-packages/gw2api/__init__.py", line 75, in __build_object_clients
    from gw2api.objects.api_version_2 import API_OBJECTS
ModuleNotFoundError: No module named 'gw2api.objects'
```

I assume this is because of a missing MANIFEST.in file, e.g.:

```
include README.rst
include LICENSE
recursive-include gw2api *.py
```

If you want, I can create it and create a new PR and then we can try again.

**Comment by JuxhinDB** [comment]
@shoeffner -- Aha, good catch! Not too familiar with PyPi unfortunately so I felt something like this would crop up. If it's very little work, do you mind showing me, via a PR how you would setup the MANIFEST.in file?

**Comment by shoeffner** [comment]
Hm, it might not be the manifest file. I just tried packaging without it using `python setup.py sdist` and the resulting tar contained all files needed, thus I think the upload should have worked fine then. How did you go on about it?

**Comment by JuxhinDB** [comment]
Actually you're right.. It seems that in a test venv I have the following paths:

```
\venv\Lib\site-packages\gw2api
\venv\Lib\site-packages\GuildWars2_API_Client-0.5.0.dist-info
```

However inside `\venv\Lib\site-packages\gw2api` I only have the `__init__.py` file and nothing else. I'll take a closer look

**Comment by JuxhinDB** [comment]
Update, egg distribution contains everything, however WHEEL is missing most of the files.

**Pull request merged**
